server:
   port: 5008 
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always  
 
    
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: batch-center
  batch:
    job:
      enabled: false
  shardingsphere:
    enabled: true
    sharding:
      default-data-source-name: ds0
      default-key-generator:
        column: id
        props:
          worker:
            id: ${workerId}
        type: SNOWFLAKE
    datasource:
      names: ds0
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://${ocp.datasource.ip:192.168.92.216}:${ocp.datasource.port:3306}/batch-center?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
        username: ${ocp.datasource.username}
        password: ${ocp.datasource.password}
        #初始化时建立物理连接的个数。初始化发生在显示调用init方法，或者第一次getConnection时
        initial-size: 5
        #最大连接数
        max-active: 50 
        #最小连接数
        min-idle: 5 
        #获取连接时最大等待时间，单位毫秒。配置了maxWait之后，缺省启用公平锁，并发效率会有所下降，如果需要可以通过配置useUnfairLock属性为true使用非公平锁。
        max-wait: 60000
        #用来检测连接是否有效的sql，要求是一个查询语句，常用select 'x'。如果validationQuery为null，testOnBorrow、testOnReturn、testWhileIdle都不会起作用。
        validation-query: SELECT 1 FROM DUAL
        #单位：秒，检测连接是否有效的超时时间。底层调用jdbc Statement对象的void setQueryTimeout(int seconds)方法
        validation-query-timeout: 5 
        #建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
        test-while-idle: true 
        #申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
        test-on-borrow: false 
        #归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
        test-on-return: false 
        #有两个含义： 1) Destroy线程会检测连接的间隔时间，如果连接空闲时间大于等于minEvictableIdleTimeMillis则关闭物理连接。 2) testWhileIdle的判断依据，详细看testWhileIdle属性的说明
        time-between-eviction-runs-millis: 60000   
        # 连接保持空闲而不被驱逐的最小时间
        min-evictable-idle-time-millis: 300000 
        #连接池中的minIdle数量以内的连接，空闲时间超过minEvictableIdleTimeMillis，则会执行keepAlive操作。
        keep-alive: true 
         # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
        # 合并多个DruidDataSource的监控数据
        useGlobalDataSourceStat: true 
        #是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭。
        pool-prepared-statements: false 
         #要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。在Druid中，不会存在Oracle下PSCache占用内存过多的问题，可以把这个数值配置大一些，比如说100
        max-pool-prepared-statement-per-connection-size: 100
        #是否到期强制删除,避免某个连接长时间阻塞无法回收
        remove-abandoned: true
        #租用时长，Druid避免连泄露 s
        remove-abandoned-timeout: 120  
        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        filters: stat,wall
        #合并多个DruidDataSource的监控数据
        use-global-data-source-stat: false
        #配置stat-view-servlet
        stat-view-servlet:
          #允许开启监控
          enabled: true
          #监控面板路径
          url-pattern: /druid/*
        
mybatis-plus:
  mapper-locations: com/open/**/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.open.capacity.common.model
  global-config:
    banner: false   
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl 
 

logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
#    com.neusoft: DEBUG     
#    com.netflix: DEBUG                    #用于心跳检测输出的日志    


  
 