spring:
  application:
    name: liteflow-mysql

liteflow:
  #liteflow是否开启，默认为true
  enable: true
  #liteflow的banner打印是否开启
  print-banner: false
  rule-source-ext-data-map:
#    url: jdbc:mysql://${ocp.datasource.ip:192.168.92.216}:3306/poseidon?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
#    driverClassName: com.mysql.cj.jdbc.Driver
#    username: ${ocp.datasource.username}
#    password: ${ocp.datasource.password}
    applicationName: demo
    #以下是chain表的配置，这个一定得有
    chainTableName: chain
    chainApplicationNameField: application_name
    chainNameField: chain_name
    elDataField: el_data
    #以下是script表的配置，如果你没使用到脚本，下面可以不配置
    scriptTableName: script
    scriptApplicationNameField: application_name
    scriptIdField: script_id
    scriptNameField: script_name
    scriptDataField: script_data
    scriptTypeField: script_type
    scriptLanguageField: script_language